---
name: Allow Workflow Run
on:
  workflow_call:
    outputs:
      should_run:
        description: "Whether the workflow should run"
        value: ${{ jobs.check-should-run.outputs.should_run }}

permissions:
  contents: read
  pull-requests: write

jobs:
  check-should-run:
    name: Check Should Run
    runs-on: ubuntu-24.04
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          repository: microsoft/CAIRA
          ref: main
          fetch-depth: 0
          sparse-checkout: |
            .github/scripts
          sparse-checkout-cone-mode: true

      - name: üîç Check if the workflows are allowed to run
        id: check
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ github.token }}
          script: |
            const { default: script } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/test_terraform.mjs`)
            await script({context, github, core})
